### ISSUE TITLE
Add option SemialgebraicComplex to compute only minimal functions 

### ISSUE THREAD

**Issue by ComboProblem** [mkoeppe/cutgeneratingfunctionology#80]
For problems in the Gomory Johnson Model, add an option to SemialgebraicComplex to enable testing for only minimal functions functions rather than assuming the default behavior of extremity testing.

**Comment by mkoeppe** [comment]
Example?

**Comment by ComboProblem** [comment]
In `SemialgebraicComplex` in the paragmetric.sage file, there is an option for `find_region_type` and the doc string states to set this to `None` for functions from the Gomory Johnson model. By default, `SemialgebraicComplex` uses the `find_region_type_igp` method which defaults to computing extreme functions when used in a method like `bfs_completion` (as far as I'm aware). It is unclear (to me) how to how to change this option for `find_region_type` so that `find_region_types_igp` finds minimal functions only rather than also searching for extreme functions. 

As a particular improvement, it would be nice if the command could be something like `clx = SemialgebraicComplex(family_of_gomory_johnson_functions, list_of_parameters, model="minimal_only")`  which would compute the proof complex for the parameters taking into consideration only minimal, not-minimal, and not-constructible regions. Or it would be nice to add documentation on how to change the behavior  of `find_region_type_igp` as an argument to SemialgebraicComplex so the above could be accomplished.

**Comment by ComboProblem** [comment]
Fixed with updated documentation.
